### PR TITLE
Convert to Java and fix running on recent Jenkins versions

### PR DESCRIPTION
**Pull request by orgads**
Fixes https://issues.jenkins.io/browse/JENKINS-72701

### Testing done

```[tasklist]
### Submitter checklist
- [X] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [X] Ensure that the pull request title represents the desired changelog entry
- [X] Please describe what you did
- [X] Link to relevant issues in GitHub or Jira
- [X] Link to relevant pull requests, esp. upstream and downstream changes
- [X] Ensure you have provided tests - that demonstrates feature works or fixes the issue
```

### CODE REVIEW

**Comment by orgads** [comment]
Looks like github is not that good with renames, even when put in a separate commit...

All the important changes are in 737c7e3457. Please review it.

**Comment by orgads** [comment]
The heavy lifting was done with https://www.codeconvert.ai/groovy-to-java-converter. I tweaked it later to fix the build and tests.

**Review by sue445 — CHANGES_REQUESTED** [review]
Could you have all `src/main/groovy/**/*.java` files moved to `src/main/java/` ?

Other are LGTM

**Comment by orgads** [comment]
Done

**Pull request merged**
