### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by orgads**
### Testing done

Replaces #35, #45, #48, #49 and actually fixes the build.

```[tasklist]
### Submitter checklist
- [X] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [X] Ensure that the pull request title represents the desired changelog entry
- [X] Please describe what you did
- [X] Link to relevant issues in GitHub or Jira
- [X] Link to relevant pull requests, esp. upstream and downstream changes
- [X] Ensure you have provided tests - that demonstrates feature works or fixes the issue
```

### CODE REVIEW

**Comment by sue445** [comment]
@orgads Thank you patch! I'II merge this after build is fixed 🙏

**Comment by orgads** [comment]
Where is the build configured? I think it should use java 11 instead of 1.8.

**Comment by sue445** [comment]
Build configuration is here
https://github.com/jenkinsci/yaml-axis-plugin/blob/49b5fdf1f6395c5db9fc6d9ada7a6ecde404caa5/Jenkinsfile

**Comment by orgads** [comment]
@sue445 It looks like Jenkinsfile is used from master, I can't change it.

https://ci.jenkins.io/job/Plugins/job/yaml-axis-plugin/job/PR-54/5/console
```
08:29:30  Loading trusted files from base branch master at 49b5fdf1f6395c5db9fc6d9ada7a6ecde404caa5 rather than 821fded7ade2aff11662b7e6da9a3793a693bfb0
08:29:30  Obtained Jenkinsfile from 49b5fdf1f6395c5db9fc6d9ada7a6ecde404caa5
08:29:31  ‘Jenkinsfile’ has been modified in an untrusted revision
```

**Comment by MarkEWaite** [comment]
I launched the build with the revised Jenkinsfile from @orgads .  Checks pass.  Thanks for a very nice contribution!

**Comment by orgads** [comment]
Great! Once you merge this PR, I'll rebase the other one (convert to Java) to ease its review process.

**Review by sue445 — APPROVED** [review]
LGTM!

**Pull request merged**
